# Project information
site_name: Dockside
site_url: https://github.com/newsnowlabs/dockside
site_description: >-
  A tool for provisioning lightweight access-controlled IDEs, staging environments and sandboxes - aka 'devtainers' - on local machine, self-hosted on-premises (on raw metal or VM) or in the cloud

# Filesystem configuration
site_dir: '/home/newsnow/dockside/app/server/nginx/html/docs/'

# Repository
repo_name: NewsNow Labs/Dockside
repo_url: https://github.com/newsnowlabs/dockside
edit_uri: 'edit/main/docs/'

# Copyright
copyright: Copyright &copy; 2017 - 2021 NewsNow Publishing Limited and contributors

# Theme configuration
theme:
  name: material
  logo: images/android-chrome-256x256.png
  favicon: images/favicon.ico
  features:
    - tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  homepage: /docs/

# Plugins
plugins:
  - search # necessary for search to work
#  - awesome-pages

# Extensions
markdown_extensions:
  - smarty
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
## Disabled for now, as not Github-compatible
#  - admonition
#  - footnotes
#  - pymdownx.tasklist:
#      custom_checkbox: true
#  - pymdownx.tabbed
#  - pymdownx.details

nav:
  - Introduction: README.md
  - Usage: usage.md
  - Setup: setup.md
  - Upgrading: upgrading.md
  - Security: securing.md
  - Extensions:
    - Extensions: extensions.md
    - LXCFS: extensions/lxcfs.md
    - Multiarch: extensions/multiarch.md
    - Sysbox: extensions/runtimes/sysbox.md
    - Backups: extensions/backups.md
  - Case Studies: case-studies/NewsNow.md
  - Roadmap: roadmap.md
  - Developing:
    - Developing: developing.md
    - Building an image: building-image.md